language: c

cache:
  ccache: true

os:
  - linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - cmake

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - compiler: clang
      env: BUILD_TYPE="Release"
    - compiler: clang
      env: BUILD_TYPE="Debug"
    - compiler: gcc
      env: BUILD_TYPE="Release"
    - compiler: gcc
      env: BUILD_TYPE="Debug"

script:
 - cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}"
 - make
